### ISSUE TITLE
Feature request: "X" checkmarks

### ISSUE THREAD

**Issue by 12people** [davigmacode/flutter_animated_checkmark#1]
I'm working on a habit app where days are represented by:
- a checkmark if the habit was completed
- an empty box if the box has not been interacted with yet
- an X if the habit was not completed

Since X can be used in checkboxes somewhat commonly (whether in a positive or in a negative sense), it might be useful for others using this library as well.

**Comment by davigmacode** [comment]
Thanks for the feedback, that's a good idea! I just updated the package. You can check it out, but I think there's room for improvement in the animation between the :heavy_check_mark: and the :x:.

**Comment by 12people** [comment]
@davigmacode 
Wonderful, thank you so much!
(Sorry for the late response, I've been quite busy with other things and only now have gotten back into this project.)
